### ISSUE TITLE
When highlighting a span that includes an existing highlight, duplicate text is inserted 

### ISSUE THREAD

**Issue by ChatBotMatt** [kevin91nl/text-highlighter#1]
Before: 
![image](https://user-images.githubusercontent.com/16762005/185155503-d16224d3-4f35-4d32-b4ca-941f8984969e.png)

After highlighting "week. WidgetInc was founded by John Widgeton"
![image](https://user-images.githubusercontent.com/16762005/185155627-614c6ca3-74a6-4bc0-939d-773134244e44.png)

It appears to duplicate the pre-highlighted text and insert it following the newly-highlighted text (so "week", in this case). If you click on the new highlight and remove it, the duplicate text disappears too.

**Comment by ChatBotMatt** [comment]
Looks like this is due to (partial) duplicate annotations existing. I can fix that by deduplicating them, but can't actually get it to change within the widget because Streamlit won't let me update the widget's value dynamically.

**Comment by ChatBotMatt** [comment]
Hi, sorry about that, I may have been unclear.

In your example, if you highlight "Hello world!" at the start (so that it overlaps the "Hello" highlight, it will **create** duplicate text, which is my problem.

**Comment by kevin91nl** [comment]
Ah, thank you for the clarification. It is resolved in the latest version of text-highlighter (`pip install --upgrade text-highlighter`).

In version 0.0.7 of text highlighter, one or multiple overlapping highlights will be deselected. This overcomes the issue with duplicated text and also works in scenarios for more than two overlapping highlights.

**Comment by ChatBotMatt** [comment]
That's great, thank you! Really appreciate the fast response.
