### ISSUE TITLE
order label assignment and align them with previously used labels

### ISSUE THREAD

**Issue by davidberenstein1957** [kevin91nl/text-highlighter#5]
HI @kevin91nl, this is awesome and exactly what I was looking for, however, I get some minor issues with label colors. If I pre-assign annotations without a color, they all get the colour blue, and if I later assign the same label, it gets the colour red.

![image](https://user-images.githubusercontent.com/25269220/218303044-59282178-d0fd-4f9f-950c-96770c540ef9.png)

**Comment by kevin91nl** [comment]
Thank you @davidberenstein1957 for your feedback!

From version 0.0.9, you can use the following to specify the color labels:
```
result = text_highlighter(
    text="Cats and dogs in the Netherlands are awesome!",
    labels=[
        ("ANIMAL", "yellow"),
        ("LOCATION", "green")
    ],
    annotations=[
        {
            "start": 0,
            "end": 4,
            "text": "and",
            "tag": "ANIMAL",
            "color": "yellow"
        }
    ]
)
```

Here, all `ANIMAL` tags will become yellow and all `LOCATION` tags will become green.
