### ISSUE TITLE
Incorporating Newline Characters

### ISSUE THREAD

**Issue by cskor** [kevin91nl/text-highlighter#8]
I have a piece of text with newline characters, but the newline characters are getting ignored. What character(s) should I be using to signal I want a newline in the text highlighter?

Example:

I would expect the output to be on two lines.

`results = text_highlighter('testing with \n a newline', [('Good', '#ACFA97'), ('Bad', '#F39682)])`

<img width="248" alt="Screen Shot 2023-09-25 at 2 44 47 PM" src="https://github.com/kevin91nl/text-highlighter/assets/40743983/3bf5391f-c023-4c0a-987b-0587cff3c645">

**Comment by dadamson** [comment]
After stabbing around, I think if y'all add something like
```
span{
  white-space: pre;
}
```
to https://github.com/kevin91nl/text-highlighter/blob/main/text_highlighter/frontend/src/style.css I think it'll render our newlines.

(I just edited the collapsed CSS directly in my installed site-packages)
