### ISSUE TITLE
Feature Request: Markdown and LaTex Support

### ISSUE THREAD

**Issue by juliuskittler** [kevin91nl/text-highlighter#9]
Thanks a lot for the component, I really like it so far and it works very well for plain text.

**Currently**, when the text is formatted as Markdown or as LaTeX the text selection also seems possible. However, the text does not get rendered correctly as Markdown / LaTeX in the user interface.

**Hence my feature request:** it would be great to have an argument like 'format', which can take ['text', 'markdown', 'latex']. For the latter two, the text in the user interface should be rendered with "st.markdown" or with "st.latex". The text selection itself should work just as it does currently. Ideally, this should also work well for tables and formulas.

PS.: I think this request goes in the direction of the issue https://github.com/kevin91nl/text-highlighter/issues/8. However, it goes beyond just rendering new line characters.

**Comment by kevin91nl** [comment]
Thank you for your suggestion, that would be a great addition! I don't have the time to implement this at the moment, but feel free to create a pull request.
